
package Vista;

import Modelo.ImplementacionRedSocial;
import Modelo.PublicacionCompartida;
import Modelo.PublicacionOriginal;

/**
 *
 * @author ASUS
 */
public class SeleccionPost extends javax.swing.JFrame
{
    
    ImplementacionRedSocial ReferenciaRedSocial;
    int IdPreguntaSeleccionada;
    
    /**
     * Creates new form PreguntaSeleccionada
     * @param RS
     * @param ID
     */
    public SeleccionPost(ImplementacionRedSocial RS, int ID)
    {
        this.ReferenciaRedSocial = RS;
        this.IdPreguntaSeleccionada = ID;
        initComponents();
        this.setResizable(false);
        this.setLocationRelativeTo(null);
        this.jButton2.setFocusable(false);
        this.jButton1.setFocusable(false);
        RellenarDatosVentana();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(254, 249, 231));
        jPanel1.setForeground(new java.awt.Color(133, 193, 233));
        jPanel1.setPreferredSize(new java.awt.Dimension(1280, 720));
        jPanel1.setRequestFocusEnabled(false);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Responde a", "Fecha", "Autor", "Contenido"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setRequestFocusEnabled(false);
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setResizable(false);
            jTable1.getColumnModel().getColumn(0).setPreferredWidth(20);
            jTable1.getColumnModel().getColumn(1).setResizable(false);
            jTable1.getColumnModel().getColumn(1).setPreferredWidth(20);
            jTable1.getColumnModel().getColumn(2).setResizable(false);
            jTable1.getColumnModel().getColumn(2).setPreferredWidth(20);
            jTable1.getColumnModel().getColumn(3).setResizable(false);
            jTable1.getColumnModel().getColumn(3).setPreferredWidth(60);
            jTable1.getColumnModel().getColumn(4).setResizable(false);
            jTable1.getColumnModel().getColumn(4).setPreferredWidth(600);
        }

        jButton1.setText("Volver");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(133, 193, 233));
        jLabel1.setText("Informacion post seleccionado");
        jLabel1.setRequestFocusEnabled(false);

        jLabel2.setForeground(new java.awt.Color(133, 193, 233));
        jLabel2.setText("ID:");
        jLabel2.setRequestFocusEnabled(false);

        jLabel3.setForeground(new java.awt.Color(133, 193, 233));
        jLabel3.setText("ID");
        jLabel3.setRequestFocusEnabled(false);

        jLabel4.setForeground(new java.awt.Color(133, 193, 233));
        jLabel4.setText("ID original:");
        jLabel4.setRequestFocusEnabled(false);

        jLabel5.setForeground(new java.awt.Color(133, 193, 233));
        jLabel5.setText("IDOR");
        jLabel5.setRequestFocusEnabled(false);

        jLabel6.setForeground(new java.awt.Color(133, 193, 233));
        jLabel6.setText("Tipo de publicacion:");
        jLabel6.setRequestFocusEnabled(false);

        jLabel7.setForeground(new java.awt.Color(133, 193, 233));
        jLabel7.setText("Tipo");
        jLabel7.setRequestFocusEnabled(false);

        jLabel8.setForeground(new java.awt.Color(133, 193, 233));
        jLabel8.setText("Fecha creacion:");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setRequestFocusEnabled(false);
        jScrollPane2.setViewportView(jTextArea1);

        jLabel9.setForeground(new java.awt.Color(133, 193, 233));
        jLabel9.setText("dd/mm/yyyy");
        jLabel9.setRequestFocusEnabled(false);

        jLabel10.setForeground(new java.awt.Color(133, 193, 233));
        jLabel10.setText("Autor: ");
        jLabel10.setRequestFocusEnabled(false);

        jLabel11.setForeground(new java.awt.Color(133, 193, 233));
        jLabel11.setText("Usuario");
        jLabel11.setRequestFocusEnabled(false);

        jLabel12.setForeground(new java.awt.Color(133, 193, 233));
        jLabel12.setText("Contenido publicacion:");
        jLabel12.setRequestFocusEnabled(false);

        jLabel13.setForeground(new java.awt.Color(133, 193, 233));
        jLabel13.setText("Destinado a:");
        jLabel13.setRequestFocusEnabled(false);

        jButton2.setText("Compartir post");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel15.setForeground(new java.awt.Color(133, 193, 233));
        jLabel15.setText("Comentarios:");
        jLabel15.setRequestFocusEnabled(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(140, 140, 140)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1000, Short.MAX_VALUE)
                    .addComponent(jLabel12)
                    .addComponent(jScrollPane2)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 900, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel15)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(237, 237, 237)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel1)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(12, 12, 12)
                                        .addComponent(jLabel6)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel7)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel8)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel9)
                                        .addGap(98, 98, 98))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel3)
                                .addGap(53, 53, 53)
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel5)))
                        .addGap(5, 5, 5)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(140, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1)
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11))
                .addGap(30, 30, 30)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(113, 113, 113)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addGap(51, 51, 51))
        );

        jButton1.getAccessibleContext().setAccessibleName("jButton1");
        jLabel1.getAccessibleContext().setAccessibleName("jLabel1");
        jLabel2.getAccessibleContext().setAccessibleName("jLabel2");
        jLabel3.getAccessibleContext().setAccessibleName("jLabel3");
        jLabel4.getAccessibleContext().setAccessibleName("jLabel4");
        jLabel7.getAccessibleContext().setAccessibleName("jLabel7");
        jLabel8.getAccessibleContext().setAccessibleName("jLabel8");
        jLabel9.getAccessibleContext().setAccessibleName("jLabel9");
        jLabel10.getAccessibleContext().setAccessibleName("jLabel10");
        jLabel11.getAccessibleContext().setAccessibleName("jLabel11");
        jLabel12.getAccessibleContext().setAccessibleName("jLabel12");
        jButton2.getAccessibleContext().setAccessibleName("jButton2");
        jTextField1.getAccessibleContext().setAccessibleName("jTextField1");
        jLabel15.getAccessibleContext().setAccessibleName("jLabel15");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    //Boton volver
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        //Se instancia ventana de sesion iniciada
        SesionIniciada Retorno = new SesionIniciada(this.ReferenciaRedSocial);
        
        //Se finaliza muestreo ventana actual
        this.setVisible(false);
        
        //Se inicia muestro ventana instanciada
        Retorno.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    // Boton Compartir post presionado
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        
        //Se instancia ventana de sesion iniciada
        VentanaShare DirigidoACompartir = new VentanaShare(this.ReferenciaRedSocial, this.IdPreguntaSeleccionada);
        
        //Se finaliza muestreo ventana actual
        this.setVisible(false);
        
        //Se inicia muestro ventana instanciada
        DirigidoACompartir.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void RellenarDatosVentana()
    {
        int IndiceUsuarioPreguntaOr = this.ReferenciaRedSocial.ReferenciarUsuarioPublicacionOr(this.IdPreguntaSeleccionada);
        int IndiceUsuarioPreguntaComp = this.ReferenciaRedSocial.ReferenciarUsuarioPublicacionComp(this.IdPreguntaSeleccionada);
        
        if(!(IndiceUsuarioPreguntaOr == -1))
        {
            int PublicacionOrApuntada = this.ReferenciaRedSocial.getUsuariosRegistrados().get(IndiceUsuarioPreguntaOr).getPublicacionOriginalPorId(this.IdPreguntaSeleccionada);
            PublicacionOriginal OR = this.ReferenciaRedSocial.getUsuariosRegistrados().get(IndiceUsuarioPreguntaOr).getPublicacionesOrUsuario().get(PublicacionOrApuntada);
            
            //Realizar seteos de labels
            
            this.jLabel3.setText(Integer.toString(OR.getIdPublicacion()));
            this.jLabel5.setText("0");
            this.jLabel7.setText(OR.getTipoPublicacion());
            this.jLabel9.setText(OR.getFechaPublicacion());
            this.jLabel11.setText(OR.getAutorPublicacion());
            this.jTextArea1.setText(OR.getContenidoPublicacion());
            
            //jTextField debe recibir string con destinatarios, no lista
            String DestinosEnString = "";
            for(int i = 0; i < OR.getUsuariosDirigidos().size(); i++)
            {DestinosEnString += OR.getUsuariosDirigidos().get(i)+" ";}
            
            //Se asigna string resultante
            this.jTextField1.setText(DestinosEnString);
        }
        
        else
        {
            int PublicacionCompApuntada = this.ReferenciaRedSocial.getUsuariosRegistrados().get(IndiceUsuarioPreguntaOr).getPublicacionCompartidaPorId(this.IdPreguntaSeleccionada);
            PublicacionCompartida COMP = this.ReferenciaRedSocial.getUsuariosRegistrados().get(IndiceUsuarioPreguntaOr).getPublicacionesCompUsuario().get(PublicacionCompApuntada);
            
            //Realizar seteos de labels
            
            this.jLabel3.setText(Integer.toString(COMP.getIdPublicacion()));
            this.jLabel5.setText(Integer.toString(COMP.getIdPublicacionCompartida()));
            this.jLabel7.setText(COMP.getTipoPublicacion());
            this.jLabel9.setText(COMP.getFechaPublicacion());
            this.jLabel11.setText(COMP.getAutorPublicacion());
            this.jTextArea1.setText(COMP.getContenidoPublicacion());
            
            //jTextField debe recibir string con destinatarios, no lista
            String DestinosEnString = "";
            for(int i = 0; i < COMP.getUsuariosDirigidos().size(); i++)
            {DestinosEnString += COMP.getUsuariosDirigidos().get(i)+" ";}
            
            //Se asigna string resultante
            this.jTextField1.setText(DestinosEnString);
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
