
package Vista;

import Modelo.ImplementacionRedSocial;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author ASUS
 */
public class VentanaShare extends javax.swing.JFrame {

    ImplementacionRedSocial ReferenciaRedSocial;
    int IdPreguntaSeleccionada;
    
    /**
     * Creates new form VentanaShare
     * @param RS
     * @param ID
     */
    public VentanaShare(ImplementacionRedSocial RS, int ID)
    {
        this.ReferenciaRedSocial = RS;
        this.IdPreguntaSeleccionada = ID;
        initComponents();
        this.jLabel3.setText(Integer.toString(ID));
        this.setResizable(false);
        this.setLocationRelativeTo(null);
        this.jButton1.setFocusable(false);
        this.jButton2.setFocusable(false);
        MostrarContactosEnTabla();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(254, 249, 231));
        jPanel1.setForeground(new java.awt.Color(133, 193, 233));
        jPanel1.setPreferredSize(new java.awt.Dimension(1280, 720));
        jPanel1.setRequestFocusEnabled(false);

        jButton1.setText("Volver");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Compartir");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Contactos"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setRequestFocusEnabled(false);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setResizable(false);
        }

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(133, 193, 233));
        jLabel1.setText("Compartir post");
        jLabel1.setRequestFocusEnabled(false);

        jTextField1.setForeground(new java.awt.Color(133, 193, 233));
        jTextField1.setRequestFocusEnabled(false);

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(133, 193, 233));
        jLabel2.setText("ID pregunta seleccionada:");

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(133, 193, 233));
        jLabel3.setText("ID");
        jLabel3.setRequestFocusEnabled(false);

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(133, 193, 233));
        jLabel4.setText("Lista contactos:");
        jLabel4.setRequestFocusEnabled(false);

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(133, 193, 233));
        jLabel5.setText("Destinos seleccionados:");
        jLabel5.setRequestFocusEnabled(false);

        jButton3.setText("Agregar");
        jButton3.setRequestFocusEnabled(false);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Borrar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel6.setForeground(new java.awt.Color(254, 249, 231));
        jLabel6.setText("Apoyo");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(200, 200, 200)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addGap(200, 200, 200))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(511, 511, 511)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(400, 400, 400)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jButton3)
                                .addGap(152, 152, 152)
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton4))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(56, 56, 56)
                                .addComponent(jLabel3))
                            .addComponent(jLabel4)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 480, Short.MAX_VALUE)
                            .addComponent(jLabel5)
                            .addComponent(jTextField1))))
                .addContainerGap(400, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addGap(24, 24, 24)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3)
                    .addComponent(jButton4)
                    .addComponent(jLabel6))
                .addGap(28, 28, 28)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(74, 74, 74)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addGap(73, 73, 73))
        );

        jLabel1.getAccessibleContext().setAccessibleName("jLabel1");
        jTextField1.getAccessibleContext().setAccessibleName("jTextField1");
        jLabel2.getAccessibleContext().setAccessibleName("jLabel2");
        jLabel3.getAccessibleContext().setAccessibleName("jLabel3");
        jLabel4.getAccessibleContext().setAccessibleName("jLabel4");
        jButton3.getAccessibleContext().setAccessibleName("jButton3");
        jButton4.getAccessibleContext().setAccessibleName("jButton4");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Boton volver
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        //Se instancia ventana de sesion iniciada
        SeleccionPost RegresoAInfoPost = new SeleccionPost(this.ReferenciaRedSocial, this.IdPreguntaSeleccionada);
        
        //Se finaliza muestreo ventana actual
        this.setVisible(false);
        
        //Se inicia muestro ventana instanciada
        RegresoAInfoPost.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed
    
    //Boton compartir
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        
        //Procesar arraylist post
        ArrayList<String> DestinosShare = new ArrayList<>();
        String[] DestinosIngresados;
        
        if(!this.jTextField1.getText().equals(""))
        {
            DestinosIngresados = jTextField1.getText().split(" ");
            for(int i = 0; i < DestinosIngresados.length; i++)
            {DestinosShare.add(DestinosIngresados[i]);}
        }

        // Se llama a RF Share, con los datos ingresados por los campos de la ventana
        String Resultado = this.ReferenciaRedSocial.Share(Integer.parseInt(this.jLabel3.getText()), DestinosShare);
        
        // Se presenta resultado en mensaje emergente
        JOptionPane.showMessageDialog(this, Resultado);
            
        // Se instancia ventana de sesion iniciada
        SesionIniciada VentanaConSesion = new SesionIniciada(this.ReferenciaRedSocial);
            
        // Finalizar muestreo ventana actual
        this.setVisible(false);
            
        //Se inicia muestreo ventana instanciada
        VentanaConSesion.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed
    
    //Boton agregar
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        
        //Se recupera y divide el string que representa los destinos seleccionados hasta el momento de presionar el boton agregar
        String[] DestinosSeleccionados = jTextField1.getText().split(" ");
        boolean DestinoSeleccionado = false; //Booleano apoyo
        for(String DestinoActual : DestinosSeleccionados) //Se recorre el arreglo de destinos seleccionados previamente
        {
            if(jLabel6.getText().equals(DestinoActual)) //Si el destino ya fue agregado, se cambia el valor booleano a verdadero y se corta ciclo
            {
                DestinoSeleccionado = true;
                break;
            }
        }
        //Si el destino fue seleccionado previamente, se advierte de la situacion por ventana JOptionPane
        if(DestinoSeleccionado)
        {JOptionPane.showMessageDialog(this, "Destino ya esta seleccionado!", "Error", JOptionPane.ERROR_MESSAGE);}
        else //Caso contrario, se agrega al gran string la nueva etiqueta seleccionada
        {jTextField1.setText(jTextField1.getText()+" "+jLabel6.getText());}
    }//GEN-LAST:event_jButton3ActionPerformed
    
    //Boton borrar
    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        
        //Se recupera el string almacenado en la ultima casilla, dividiendose este por los espacios entre etiquetas
        String[] currentLabels = jTextField1.getText().split(" ");
        String returnString = "";
        
        //Se crea el string retorno, pero sin el ultimo elemento
        for(int i = 0; i < currentLabels.length - 1; i++)
        {
            returnString+=currentLabels[i];
            if(!(i+1 == currentLabels.length-1)) //Si no se ha llegado al penultimo elemento, se agrega un espacio entre etiquetas
            {returnString+=" ";}
        }
        
        //Se asigna el string actualizado
        jTextField1.setText(returnString);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        //Obtener los datos del post seleccionado
        int IndicePostSeleccionado = jTable1.getSelectedRow(); //Indice en la tabla del post seleccionado
        TableModel ModeloTabla = jTable1.getModel(); //Obtencion de modelo de tabla para obtencion de datos
        
        //Se recupera destino seleccionado
        String DestinoSeleccionado = ModeloTabla.getValueAt(IndicePostSeleccionado, 0).toString();
        
        //Se asigna a jLabel invisible
        this.jLabel6.setText(DestinoSeleccionado);
    }//GEN-LAST:event_jTable1MouseClicked

    private void MostrarContactosEnTabla()
    {
        //Modelo tabla
        DefaultTableModel row = (DefaultTableModel)jTable1.getModel();

        //Fila de elementos a asignar en la tabla
        Object tempRow[] = new Object[1];
        
        //Indice en lista usuarios de usuario logueado
        int IndiceUsuarioLogueado = this.ReferenciaRedSocial.getUsuarioViaUsername(this.ReferenciaRedSocial.getUsuarioLogueado());
        
        //Obtener contactos usuario logueado
        ArrayList<String> ContactosUsuarioLogueado = this.ReferenciaRedSocial.getUsuariosRegistrados().get(IndiceUsuarioLogueado).getSeguidosUsuario();
        
        //Se recorre los contactos del usuario logueado
        for(int i = 0; i < ContactosUsuarioLogueado.size(); i++)
        {
            tempRow[0] = ContactosUsuarioLogueado.get(i); //Nombre contacto usuario logueado se agrega en unica casilla fila
            row.addRow(tempRow); //Se agrega a la tabla
        } 
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
