package Vista;

import Modelo.ImplementacionRedSocial;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author ASUS
 */
public class VentanaPost extends javax.swing.JFrame {

    ImplementacionRedSocial ReferenciaRedSocial;
    
    /**
     * Creates new form VentanaPost
     * @param RS
     */
    public VentanaPost(ImplementacionRedSocial RS)
    {
        this.ReferenciaRedSocial = RS;
        initComponents();
        this.setResizable(false);
        this.setLocationRelativeTo(null);
        this.jButton1.setFocusable(false);
        this.jButton2.setFocusable(false);
        this.jButton3.setFocusable(false);
        this.jButton4.setFocusable(false);
        this.jButton2.setVisible(false);
        InicializarJComboBox();
        MostrarContactosEnTabla();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(254, 249, 231));
        jPanel1.setPreferredSize(new java.awt.Dimension(1280, 720));
        jPanel1.setRequestFocusEnabled(false);

        jButton1.setText("Volver");
        jButton1.setRequestFocusEnabled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Publicar");
        jButton2.setRequestFocusEnabled(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(133, 193, 233));
        jLabel1.setText("Realizar post");
        jLabel1.setRequestFocusEnabled(false);

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(133, 193, 233));
        jLabel2.setText("Contenido post");
        jLabel2.setRequestFocusEnabled(false);

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(133, 193, 233));
        jLabel3.setText("Agregar destinos:");
        jLabel3.setRequestFocusEnabled(false);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setRequestFocusEnabled(false);
        jTextArea1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextArea1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTextArea1);

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(133, 193, 233));
        jLabel4.setText("Tipo publicacion");
        jLabel4.setRequestFocusEnabled(false);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Contactos"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setRequestFocusEnabled(false);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setResizable(false);
        }

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox1.setRequestFocusEnabled(false);
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(133, 193, 233));
        jLabel5.setText("Destinos seleccionados:");
        jLabel5.setRequestFocusEnabled(false);

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(133, 193, 233));
        jLabel6.setText("Tipo seleccionado:");
        jLabel6.setRequestFocusEnabled(false);

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(133, 193, 233));
        jLabel7.setText("null");
        jLabel7.setRequestFocusEnabled(false);

        jTextField1.setRequestFocusEnabled(false);

        jButton3.setText("Agregar");
        jButton3.setRequestFocusEnabled(false);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Borrar");
        jButton4.setRequestFocusEnabled(false);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel8.setForeground(new java.awt.Color(254, 249, 231));
        jLabel8.setText("Destino");
        jLabel8.setRequestFocusEnabled(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel2)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 563, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel4)
                                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(163, 163, 163)
                                        .addComponent(jLabel6))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(219, 219, 219)
                                        .addComponent(jLabel7))
                                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addGap(376, 376, 376))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(117, 117, 117)
                                                .addComponent(jLabel8))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(90, 90, 90)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))))))))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(528, 528, 528)
                        .addComponent(jLabel1)))
                .addContainerGap(80, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel1)
                .addGap(62, 62, 62)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(37, 37, 37)
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel7))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(8, 8, 8)
                        .addComponent(jLabel5))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton4)
                        .addGap(68, 68, 68)
                        .addComponent(jLabel8)))
                .addGap(5, 5, 5)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addGap(63, 63, 63))
        );

        jButton1.getAccessibleContext().setAccessibleName("jButton1");
        jButton2.getAccessibleContext().setAccessibleName("jButton2");
        jLabel1.getAccessibleContext().setAccessibleName("jLabel1");
        jLabel2.getAccessibleContext().setAccessibleName("jLabel2");
        jLabel3.getAccessibleContext().setAccessibleName("jLabel3");
        jLabel4.getAccessibleContext().setAccessibleName("jLabel4");
        jLabel5.getAccessibleContext().setAccessibleName("jLabel5");
        jLabel6.getAccessibleContext().setAccessibleName("jLabel6");
        jLabel7.getAccessibleContext().setAccessibleName("jLabel7");
        jTextField1.getAccessibleContext().setAccessibleName("jTextField1");
        jButton3.getAccessibleContext().setAccessibleName("jButton3");
        jButton4.getAccessibleContext().setAccessibleName("jButton4");
        jLabel8.getAccessibleContext().setAccessibleName("jLabel8");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //Volver
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        //Se instancia ventana de sesion iniciada
        SesionIniciada Retorno = new SesionIniciada(this.ReferenciaRedSocial);
        
        //Se finaliza muestreo ventana actual
        this.setVisible(false);
        
        //Se inicia muestro ventana instanciada
        Retorno.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed
    
    //Boton agregar
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        //Se recupera y divide el string que representa los destinos seleccionados hasta el momento de presionar el boton agregar
        String[] DestinosSeleccionados = jTextField1.getText().split(" ");
        boolean DestinoSeleccionado = false; //Booleano apoyo
        for(String DestinoActual : DestinosSeleccionados) //Se recorre el arreglo de destinos seleccionados previamente
        {
            if(jLabel8.getText().equals(DestinoActual)) //Si el destino ya fue agregado, se cambia el valor booleano a verdadero y se corta ciclo
            {
                DestinoSeleccionado = true;
                break;
            }
        }
        //Si el destino fue seleccionado previamente, se advierte de la situacion por ventana JOptionPane
        if(DestinoSeleccionado)
        {JOptionPane.showMessageDialog(this, "Destino ya esta seleccionado!", "Error", JOptionPane.ERROR_MESSAGE);}
        else //Caso contrario, se agrega al gran string la nueva etiqueta seleccionada
        {jTextField1.setText(jTextField1.getText()+" "+jLabel6.getText());}
    }//GEN-LAST:event_jButton3ActionPerformed
    
    // Borrar
    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        
        //Se recupera y divide el string que representa los destinos seleccionados hasta el momento de presionar el boton borrar
        String[] DestinosSeleccionados = jTextField1.getText().split(" ");
        String StringRetorno = ""; //String a guardar en JTextField
        
        //Se genera el string retorno, sin el ultimo elemento
        for(int i = 0; i < DestinosSeleccionados.length - 1; i++)
        {
            StringRetorno+=DestinosSeleccionados[i];
            if(!(i+1 == DestinosSeleccionados.length-1)) //Si no se ha llegado al penultimo elemento, se agrega un espacio entre etiquetas
            {StringRetorno+=" ";}
        }
        
        //Se asigna el string actualizado
        jTextField1.setText(StringRetorno);
    }//GEN-LAST:event_jButton4ActionPerformed

    //Se presiono un destino en la tabla
    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        //Obtener los datos del post seleccionado
        int IndicePostSeleccionado = jTable1.getSelectedRow(); //Indice en la tabla del post seleccionado
        TableModel ModeloTabla = jTable1.getModel(); //Obtencion de modelo de tabla para obtencion de datos
        
        //Se recupera destino seleccionado
        String DestinoSeleccionado = ModeloTabla.getValueAt(IndicePostSeleccionado, 0).toString();
        
        //Se asigna a jLabel invisible
        this.jLabel8.setText(DestinoSeleccionado);
    }//GEN-LAST:event_jTable1MouseClicked

    //Click sobre casilla contenido post
    private void jTextArea1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextArea1MouseClicked
        this.jTextArea1.setFocusable(true);
    }//GEN-LAST:event_jTextArea1MouseClicked

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        this.jLabel7.setText(this.jComboBox1.getSelectedItem().toString());
        if(!this.jTextArea1.getText().equals(""))
        {this.jButton2.setVisible(true);}
    }//GEN-LAST:event_jComboBox1ActionPerformed
    
    // Boton publicar, se debe llamar a requerimiento funcional Post
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // Boton Iniciar sesion
        // Obtener los datos ingresados en las casillas
        String ContenidoPost = jTextArea1.getText();
        String TipoPublicacion = jLabel7.getText();
        
        //Procesar arraylist post
        ArrayList<String> DestinosPost = new ArrayList<>();
        String[] DestinosIngresados;
        
        if(!this.jTextField1.getText().equals(""))
        {
            DestinosIngresados = jTextField1.getText().split(" ");
            for(int i = 0; i < DestinosIngresados.length; i++)
            {DestinosPost.add(DestinosIngresados[i]);}
        }
        
        // Llamar a metodo Login de la red social
        String ResultadoPost = this.ReferenciaRedSocial.Post(TipoPublicacion, ContenidoPost, DestinosPost);
        
        // Mostrar resultado por pantalla
        JOptionPane.showMessageDialog(this, ResultadoPost);
            
        // Instanciar la ventana de inicio
        SesionIniciada VentanaConSesion = new SesionIniciada(this.ReferenciaRedSocial);
            
        // Finalizar muestreo ventana actual
        this.setVisible(false);
            
        // Iniciar muestreo ventana inicio
        VentanaConSesion.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed
    
    //Metodo para rellenar elementos en tabla
    private void MostrarContactosEnTabla()
    {
        //Modelo tabla
        DefaultTableModel row = (DefaultTableModel)jTable1.getModel();

        //Fila de elementos a asignar en la tabla
        Object tempRow[] = new Object[1];
        
        //Se referencia de la lista de usuarios el indice del usuario logueado
        int IndiceUsuarioLogueado = this.ReferenciaRedSocial.getUsuarioViaUsername(this.ReferenciaRedSocial.getUsuarioLogueado());
        
        //Obtener contactos usuario logueado
        ArrayList<String> ContactosUsuarioLogueado = this.ReferenciaRedSocial.getUsuariosRegistrados().get(IndiceUsuarioLogueado).getSeguidosUsuario();
        
        //Se recorre los contactos del usuario logueado
        for(int i = 0; i < ContactosUsuarioLogueado.size(); i++)
        {
            tempRow[0] = ContactosUsuarioLogueado.get(i); //Nombre contacto usuario logueado se agrega en unica casilla fila
            row.addRow(tempRow); //Se agrega a la tabla
        } 
    }
    
    //Metodo para rellenar jComboBox
    private void InicializarJComboBox()
    {
        this.jComboBox1.addItem("Texto");
        this.jComboBox1.addItem("Audio");
        this.jComboBox1.addItem("URL");
        this.jComboBox1.addItem("Foto");
        this.jComboBox1.addItem("Video");
        this.jComboBox1.removeItem("Item 1");
        this.jComboBox1.removeItem("Item 2");
        this.jComboBox1.removeItem("Item 3");
        this.jComboBox1.removeItem("Item 4");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
